backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "static"

collections:
  - name: "text"
    label: "text"
    delete: false
    files:
      - name: text
        label: text
        file: "content/text.yml"
        fields:
          - name: languages
            widget: list
            fields:
            - { name: language, widget: string }
            - { name: siteName, widget: string, required: false }
            - { name: introduction, widget: text, required: false }
            - { name: aboutHeader, widget: string, required: false }
            - { name: experienceHeader, widget: string, required: false }
            - { name: contactHeader, widget: string, required: false }
            - { name: contactIntroduction, widget: text, required: false }
            - { name: copyright, widget: string, required: false }
  - name: "about"
    label: "about"
    description: "more info about myself/work/life"
    folder: "content/_about/"
    create: true
    fields:
      - { name: language, widget: string }
      - { name: title, widget: string }
      - { name: memo, widget: markdown }
      - { name: tags, widget: relation, collection: tag, valueField: tag.*, searchFields: [tag.title], required: false }
  - name: "experience"
    label: "experience"
    description: "work and education experience in development"
    folder: "content/_experience/"
    create: true
    fields:
      - { name: language, widget: string }
      - { name: from, widget: datetime }
      - { name: to, widget: datetime }
      - { name: title, widget: string }
      - { name: memo, widget: markdown }
      - { name: link, widget: string, required: false }
      - { name: tags, widget: relation, collection: tag, valueField: tag.*, searchFields: [tag.title], required: false }
  - name: "contact"
    label: "contact"
    desciption: "ways of contacting me"
    folder: "content/_contact/"
    create: true
    fields:
      - { name: language, widget: string }
      - { name: icon, widget: string }
      - { name: link, widget: string }
      - { name: title, widget: string }
      - { name: handle, widget: string, required: false }
  - name: "tag"
    label: "tag"
    description: "tags to emphasise and link other content"
    folder: "content/_tag/"
    create: true
    fields:
      - { name: language, widget: string }
      - { name: icon, widget: string, required: false }
      - { name: animation, widget: string, required: false }
      - { name: title, widget: string }
