backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "static"

collections:
  - name: "text"
    label: "text on site"
    files:
      - label: "about"
        name: "about"
        file: "content/about.yml"
        fields:
          - { label: name, name: name, widget: string }
          - { label: introduction, name: introduction, widget: markdown }
      - label: "footer"
        name: "footer"
        file: "content/footer.yml"
        fields:
          - { label: copyright, name: copyright, widget: string }
  - name: "contact"
    label: "contact"
    folder: "content/_contact/"
    create: true
    fields:
      - { label: icon, name: icon, widget: string }
      - { label: link, name: link, widget: string }
      - { label: title, name: title, widget: string }
      - { label: handle, name: handle, widget: string, required: false }
  - label: "label"
    name: "label"
    folder: "content/_label/"
    create: true
    fields:
      - { label: icon, name: icon, widget: string }
      - { label: title, name: title, widget: string }
  - label: "experience"
    name: "experience"
    folder: "content/_experience/"
    create: true
    fields:
      - { label: from, name: from, widget: datetime }
      - { label: to, name: to, widget: datetime }
      - { label: title, name: title, widget: string }
      - { label: memo, name: memo, widget: markdown }
      - { label: link, name: link, widget: string, required: false }
      - {
        label: labels,
        name: labels,
        widget: relation,
        collection: label,
        valueField: label.*,
        searchFields: [label.title]
      }
