backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "static"

collections:
  - name: "text"
    delete: false
    files:
      - name: text
        file: "content/text.yml"
        fields:
          - name: languages
            widget: list
            fields:
            - { name: language, widget: string }
            - { name: siteName, widget: string }
            - { name: introduction, widget: text }
            - { name: copyright, widget: string }
  - name: "contact"
    label: "contacts"
    desciption: "ways of contacting me"
    folder: "content/_contact/"
    create: true
    fields:
      - { name: icon, widget: string }
      - { name: link, widget: string }
      - { name: title, widget: string }
      - { name: handle, widget: string, required: false }
  - name: "label"
    label: "labels"
    description: "labels to emphasise and link other content"
    folder: "content/_label/"
    create: true
    fields:
      - { name: icon, widget: string }
      - { name: title, widget: string }
  - label: "experience"
    name: "experience"
    folder: "content/_experience/"
    create: true
    fields:
      - { name: from, widget: datetime }
      - { name: to, widget: datetime }
      - { name: title, widget: string }
      - { name: memo, widget: markdown }
      - { name: link, widget: string, required: false }
      - {
        name: labels,
        widget: relation,
        collection: label,
        valueField: label.*,
        searchFields: [label.title]
      }
